server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
  httpexchanges:
    recording:
      enabled: true
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}